#version 450

#extension GL_EXT_control_flow_attributes : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_clustered : enable
#extension GL_KHR_shader_subgroup_shuffle : enable
#extension GL_KHR_shader_subgroup_quad : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

#define DATA_A_IQ1_S
#include "types.glsl"

layout (binding = 0) readonly buffer A {block_iq1_s data_a[];};
layout (binding = 1) readonly buffer B {float data_b[];};
layout (binding = 2) writeonly buffer D {float data_d[];};

layout (push_constant) uniform parameter
{
    uint M;
    uint N;
    uint K;
    uint stride_a;
    uint stride_b;
    uint stride_d;
} p;

const uint QK_K = 256;

float[256] dequantize_row_iq1_s(const block_iq1_s x) {
    float y[256];
    const int64_t nb = 256 / QK_K;

    const float d = x.d;
    const uint8_t qs[QK_K/8] = x.qs;
    const uint16_t qh[QK_K/32] = x.qh;

    for (int ib = 0; ib < QK_K/32; ++ib) {
        const float dl = d * (2*((qh[ib] >> 12) & 7) + 1);
        const float delta = (qh[ib] & 0x8000) != 0? -IQ1S_DELTA : IQ1S_DELTA;
        for (int l = 0; l < 4; ++l) {
            const uint16_t grid = iq1s_grid[(qs[ib*4 + l] | (((qh[ib] >> 3*l) & 7) << 8))];
            for (int j = 0; j < 8; ++j) {
                y[ib*32 + l*8 + j] = dl * (bitfieldExtract(grid, 2*j, 2) + delta);
            }
        }
    }
    return y;
}

float mul_iq1_s_data_b(const block_iq1_s x, uint k_b, uint n, float sum) {
    const float d = x.d;
    const uint8_t qs[QK_K/8] = x.qs;
    const uint16_t qh[QK_K/32] = x.qh;

    for (int ib = 0; ib < QK_K/32; ++ib) {
        const float dl = d * (2*((qh[ib] >> 12) & 7) + 1);
        const float delta = (qh[ib] & 0x8000) != 0? -IQ1S_DELTA : IQ1S_DELTA;

        float temp = 0;
        for (int l = 0; l < 4; ++l) {
            const uint16_t grid = iq1s_grid[(qs[ib*4 + l] | (((qh[ib] >> 3*l) & 7) << 8))];
            for (int j = 0; j < 8; ++j) {
                temp = fma(data_b[n*p.K + (k_b*QK_K+ib*32+l*8+j)],bitfieldExtract(grid, 2*j, 2) + delta, temp);
            }
        }
        sum = fma(dl, temp, sum);
    }
    return sum;
}

void main() {
    init_iq_shmem(gl_WorkGroupSize);

    uint m = gl_GlobalInvocationID.x;
    uint n = gl_GlobalInvocationID.y;

    float sum = 0;
    for (uint k_b = 0; k_b < p.K/QK_K; k_b++) {
        sum = mul_iq1_s_data_b(data_a[m * (p.K/QK_K) +k_b], k_b, n, sum);
    }
    data_d[n*p.M + m] = sum;
}
